### ISSUE TITLE
InstructionResult doesn't follow idiomatic Rust conventions for Result types

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-asm#49]
InstructionResult includes the following fields:

```
/// Describe a panic reason with the instruction that generated it
pub struct InstructionResult {
    reason: PanicReason,
    instruction: Instruction,
}
```

This is not a very user-friendly type because a successful script result is shown like this to users of the Rust types:
```
ScriptResult {
	result: InstructionResult {
		reason: RESERV00,
		instruction: Instruction {
			op: 0,
			ra: 0,
			rb: 0,
			rc: 0,
			rd: 0,
			imm06: 0,
			imm12: 0,
			imm18: 0,
			imm24: 0
		}
	},
	gas_used: 22
}
```
The problem with this representation is that it's not immediately obvious to users that this means the script succeeded. While the encoded form of this instruction result as a word does match the specs (`0`), users logging and debugging their transactions will just see `RESERV00` in the final receipt of their transaction and have to know what that means. Rather than using dummy default instructions and non-existent panic reasons to indicate success, we should consider using an enum similar to the result type in Rust.

This could look something like this:
```
pub enum InstructionResult {
    Success(Instruction),
    Panic {
        reason: PanicReason,
        instruction: Instruction
    }
}
```

If `InstructionResult::Success.into() == 0u64`, this would match the specs and drastically improve clarity to users of the Rust types.

**Comment by vlopes11** [comment]
Couldn't this be simplified by renaming `RESERV00` to `Success`?

This will save us from duplicating the field `instruction` (present in both variants) and also from creating another enum.

Enums should be avoided whenever possible because they force the users to create match patterns - even when they don't need that (a `matches!(Success)` is trivially reduced to `reason == Success`)

**Comment by Voxelot** [comment]
That is also a viable option and would solve the biggest pain point here.
